# An accurate boundary-integral formulation for the calculation of electrostatic forces with an implicit-solvent model

### Import libraries

In [5]:
os.chdir('..')

In [2]:
os.getcwd()

'c:\\Users\\ianad\\Desktop\\paper_PBforces'

In [1]:
import os
import numpy as np
import pbj  # 

### Import custom-functions 

In [2]:
#magnitud of a vector numpy
def mag(v):
    return np.sqrt(np.dot(v, v))

#Translation pqr
def pqr_translate(directory, protein_pqr, distance):
    'Translate along distance vector the protein .pqr file'

    protein_pqr_d = protein_pqr + '_d' + str(distance[2]) #new name with z-distance
    mesh_pqr_path = '{}/{}.pqr'.format(directory,protein_pqr)
    mesh_pqr_path_out = '{}/{}.pqr'.format(directory,protein_pqr_d)

    pqr_file = open(mesh_pqr_path, 'r')
    pqr_data = pqr_file.read().split('\n')
    pqr_t_file = open(mesh_pqr_path_out, 'w')
    for line in pqr_data:
        line = line.split()
        if len(line) == 0 or line[0] != 'ATOM':
            continue
        tx,ty,tz = distance
        x_new = float(line[5])+ float(tx)
        y_new = float(line[6])+ float(ty)
        z_new = float(line[7])+ float(tz)
        text_template = '{} {}  {}   {} {}        {: 1.3f}  {: 1.3f}  {: 1.3f}  {}  {} \n'
        pqr_t_file.write(text_template.format(line[0],line[1],line[2],line[3],line[4],x_new,y_new,z_new,line[8],line[9]))

    pqr_file.close() 
    pqr_t_file.close()

    return None

In [20]:
pqr_translate('/home/ianaddisonsmith/pbj/notebooks/tutorials/pqrs','1brs_BE_barstar',[0,0,1000])

## 1lyz

### Simulation with different mesh density (vert/Ang) (2,4,8,16)

In [8]:
mesh_vertA2_sim = [2,4,8,16]

# 1lyz simulation
for mesh_value in mesh_vertA2_sim:
    
    f = open("notebooks//tutorials//1lyz_forces_to_latex.txt", "a")
    f_terms = open("notebooks//tutorials//1lyz_forces_terms_to_latex.txt", "a")
    print('-----------------------------------')
    print('mesh value: ', mesh_value)
    
    simulation = pbj.electrostatics.Simulation()
    protein = pbj.electrostatics.Solute("notebooks//tutorials//pqrs//1lyz_amber.pqr", mesh_density=mesh_value)
    simulation.operator_assembler = 'fmm'
    protein.operator_assembler = "fmm"
    protein.rhs_constructor = "fmm"
    
    simulation.add_solute(protein)
    simulation.calculate_solvation_energy()

    # Forces with energy functional
    print('formulacion con la suma de terminos')
    simulation.calculate_solvation_forces(formulation='full')
    f_solv_full = protein.results['f_solv']
    print(protein.results['f_solv'])

    # Forces with maxwell tensor
    print('formulacion nueva')
    simulation.calculate_solvation_forces(formulation='fast')
    f_solv_fast = protein.results['f_solv']
    print(protein.results['f_solv'])
    
    f.write('%d & %.4f & %.4f & %.2f  \\\ \n'%(mesh_value,\
                                               mag(f_solv_full),\
                                               mag(f_solv_fast), \
                                               protein.results['solvation_energy']))
    f_terms.write('%d & %.4f & %.4f & %.4f & %.2f  \\\ \n'%(mesh_value,\
                                                     mag(protein.results["f_qf"]),\
                                                     mag(protein.results['f_db']),\
                                                     mag(protein.results['f_ib']),\
                                                     protein.results['solvation_energy']))
    f.close()
    f_terms.close()

-----------------------------------
mesh value:  2


 <<INFO>> Starting NanoShaper 0.7.8
 <<INFO>> Loading atoms....
 <<INFO>> Read 1960 atoms
 <<INFO>> Geometric baricenter ->  1.1479 22.3381 18.922
 <<INFO>> Grid is 105
 <<INFO>> MAX 48.4206 69.6108 66.1947
 <<INFO>> MIN -46.1248 -24.9346 -28.3507
 <<INFO>> Perfil 50 %
 <<INFO>> Rmaxdim 47.778
 <<INFO>> Allocating memory...ok!
 <<INFO>> Initialization completed
 <<INFO>> Adjusting self intersection grid 
 <<INFO>> Self intersection grid is (before) 34
 <<INFO>> Self intersection grid is 32
 <<INFO>> Allocating self intersection grid....ok!
 <<INFO>> Computing alpha shape complex....ok!
 <<INFO>> Checking 209 probes for self intersections...ok!
 <<INFO>> Surface build-up time.. 0 [s]
 <<INFO>> Probe Radius value 1.4
 <<INFO>> Number of ses cells -> 4720
 <<INFO>> Number of del_point cells -> 753
 <<INFO>> Number of regular del_edge cells -> 2335
 <<INFO>> Number of singular del_edge cells -> 0
 <<INFO>> Number of regular del_facet cel

/home/ianaddisonsmith/miniconda3/envs/pbj_dev/lib/python3.9/site-packages/pyopencl/__init__.py:274: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  warn("Non-empty compiler output encountered. Set the "
/home/ianaddisonsmith/miniconda3/envs/pbj_dev/lib/python3.9/site-packages/pyopencl/__init__.py:274: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  warn("Non-empty compiler output encountered. Set the "
/home/ianaddisonsmith/miniconda3/envs/pbj_dev/lib/python3.9/site-packages/pyopencl/__init__.py:274: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  warn("Non-empty compiler output encountered. Set the "


formulacion con la suma de terminos
[ 4.7586279   0.21241821 -2.22002159]
formulacion nueva
[-0.58587534 -0.08093112  0.19749413]
-----------------------------------
mesh value:  4


 <<INFO>> Starting NanoShaper 0.7.8
 <<INFO>> Loading atoms....
 <<INFO>> Read 1960 atoms
 <<INFO>> Geometric baricenter ->  1.1479 22.3381 18.922
 <<INFO>> Grid is 153
 <<INFO>> MAX 48.6479 69.8381 66.422
 <<INFO>> MIN -46.3521 -25.1619 -28.578
 <<INFO>> Perfil 50 %
 <<INFO>> Rmaxdim 47.778
 <<INFO>> Allocating memory...ok!
 <<INFO>> Initialization completed
 <<INFO>> Adjusting self intersection grid 
 <<INFO>> Self intersection grid is (before) 34
 <<INFO>> Self intersection grid is 32
 <<INFO>> Allocating self intersection grid....ok!
 <<INFO>> Computing alpha shape complex....ok!
 <<INFO>> Checking 209 probes for self intersections...ok!
 <<INFO>> Surface build-up time.. 0 [s]
 <<INFO>> Probe Radius value 1.4
 <<INFO>> Number of ses cells -> 4720
 <<INFO>> Number of del_point cells -> 753
 <<INFO>> Num

/home/ianaddisonsmith/miniconda3/envs/pbj_dev/lib/python3.9/site-packages/pyopencl/__init__.py:274: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  warn("Non-empty compiler output encountered. Set the "


formulacion con la suma de terminos
[ 1.79717727 -0.03273622 -0.94501039]
formulacion nueva
[-0.21285358 -0.0361619   0.08661185]
-----------------------------------
mesh value:  8


 <<INFO>> Starting NanoShaper 0.7.8
 <<INFO>> Loading atoms....
 <<INFO>> Read 1960 atoms
 <<INFO>> Geometric baricenter ->  1.1479 22.3381 18.922
 <<INFO>> Grid is 219
 <<INFO>> MAX 48.5392 69.7294 66.3133
 <<INFO>> MIN -46.2434 -25.0532 -28.4693
 <<INFO>> Perfil 50 %
 <<INFO>> Rmaxdim 47.778
 <<INFO>> Allocating memory...ok!
 <<INFO>> Initialization completed
 <<INFO>> Adjusting self intersection grid 
 <<INFO>> Self intersection grid is (before) 34
 <<INFO>> Self intersection grid is 32
 <<INFO>> Allocating self intersection grid....ok!
 <<INFO>> Computing alpha shape complex....ok!
 <<INFO>> Checking 209 probes for self intersections...ok!
 <<INFO>> Surface build-up time.. 0 [s]
 <<INFO>> Probe Radius value 1.4
 <<INFO>> Number of ses cells -> 4720
 <<INFO>> Number of del_point cells -> 753
 <<INFO>> N

## 1bpi

### Simulation with different mesh density (vert/Ang) (2,4,8,16)

In [9]:
mesh_vertA2_sim = [2,4,8,16]

# 1lyz simulation
for mesh_value in mesh_vertA2_sim:
    f = open("notebooks//tutorials//1bpi_forces_to_latex.txt", "a")
    f_terms = open("notebooks//tutorials//1bpi_forces_terms_to_latex.txt", "a")
    print('-----------------------------------')
    print('mesh value: ', mesh_value)
    
    simulation = pbj.electrostatics.Simulation()
    protein = pbj.electrostatics.Solute("notebooks//tutorials//pqrs//1bpi.pqr", mesh_density=mesh_value)
    simulation.operator_assembler = 'fmm'
    protein.operator_assembler = "fmm"
    protein.rhs_constructor = "fmm"
    
    simulation.add_solute(protein)
    simulation.calculate_solvation_energy()

    # Forces with energy functional
    print('formulacion con la suma de terminos')
    simulation.calculate_solvation_forces(formulation='full')
    f_solv_full = protein.results['f_solv']
    print(protein.results['f_solv'])

    # Forces with maxwell tensor
    print('formulacion nueva')
    simulation.calculate_solvation_forces(formulation='fast')
    f_solv_fast = protein.results['f_solv']
    print(protein.results['f_solv'])
    
    f.write('%d & %.4f & %.4f & %.2f  \\\ \n'%(mesh_value,\
                                               mag(f_solv_full),\
                                               mag(f_solv_fast), \
                                               protein.results['solvation_energy']))
    f_terms.write('%d & %.4f & %.4f & %.4f & %.2f  \\\ \n'%(mesh_value,\
                                                     mag(protein.results["f_qf"]),\
                                                     mag(protein.results['f_db']),\
                                                     mag(protein.results['f_ib']),\
                                                     protein.results['solvation_energy']))
    f.close()
    f_terms.close()

-----------------------------------
mesh value:  2


 <<INFO>> Starting NanoShaper 0.7.8
 <<INFO>> Loading atoms....
 <<INFO>> Read 892 atoms
 <<INFO>> Geometric baricenter ->  30.181 10.2855 0.166
 <<INFO>> Grid is 81
 <<INFO>> MAX 66.5446 46.6491 36.5296
 <<INFO>> MIN -6.18264 -26.0781 -36.1976
 <<INFO>> Perfil 50 %
 <<INFO>> Rmaxdim 37.138
 <<INFO>> Allocating memory...ok!
 <<INFO>> Initialization completed
 <<INFO>> Adjusting self intersection grid 
 <<INFO>> Self intersection grid is (before) 26
 <<INFO>> Self intersection grid is 16
 <<INFO>> Allocating self intersection grid....ok!
 <<INFO>> Computing alpha shape complex....ok!
 <<INFO>> Checking 128 probes for self intersections...ok!
 <<INFO>> Surface build-up time.. 0 [s]
 <<INFO>> Probe Radius value 1.4
 <<INFO>> Number of ses cells -> 2725
 <<INFO>> Number of del_point cells -> 430
 <<INFO>> Number of regular del_edge cells -> 1337
 <<INFO>> Number of singular del_edge cells -> 0
 <<INFO>> Number of regular del_facet cells 

66 warnings generated.
66 warnings generated.


formulacion con la suma de terminos
[ 0.21981494 -0.01863     0.1320418 ]
formulacion nueva
[-0.01856452 -0.02606556 -0.02945963]
-----------------------------------
mesh value:  8


 <<INFO>> Starting NanoShaper 0.7.8
 <<INFO>> Loading atoms....
 <<INFO>> Read 892 atoms
 <<INFO>> Geometric baricenter ->  30.181 10.2855 0.166
 <<INFO>> Grid is 171
 <<INFO>> MAX 67.1375 47.242 37.1225
 <<INFO>> MIN -6.77552 -26.671 -36.7905
 <<INFO>> Perfil 50 %
 <<INFO>> Rmaxdim 37.138
 <<INFO>> Allocating memory...ok!
 <<INFO>> Initialization completed
 <<INFO>> Adjusting self intersection grid 
 <<INFO>> Self intersection grid is (before) 26
 <<INFO>> Self intersection grid is 16
 <<INFO>> Allocating self intersection grid....ok!
 <<INFO>> Computing alpha shape complex....ok!
 <<INFO>> Checking 128 probes for self intersections...ok!
 <<INFO>> Surface build-up time.. 0 [s]
 <<INFO>> Probe Radius value 1.4
 <<INFO>> Number of ses cells -> 2725
 <<INFO>> Number of del_point cells -> 430
 <<INFO>> Numbe

## Two centered-charge (2q) unit spheres

### Simulation at distance 3 Ang between centers with variable grid mesh (vert/$\AA ^2$)

In [3]:
mesh_vertA2_sim = [2,4,8,16,32,64]

for mesh_value in mesh_vertA2_sim:
    
    # open a file to write the results
    f = open("results_pbj//sphere_r1q2_forces_to_latex.txt", "a")
    f_terms = open("results_pbj//sphere_r1q2_forces_terms_to_latex.txt", "a")
    print('-----------------------------------')
    print('mesh value: ', mesh_value)

    #Solvation energy alone
    simulation = pbj.electrostatics.Simulation()
    protein = pbj.electrostatics.Solute("pqrs//sphere_point_r1q2.pqr", mesh_density=mesh_value, mesh_generator="msms")
    simulation.add_solute(protein)
    simulation.calculate_solvation_energy()
    solv_energy_alone = protein.results['solvation_energy']

    #Solvation energy complex
    simulation = pbj.electrostatics.Simulation()
    protein = pbj.electrostatics.Solute("pqrs//sphere_point_r1q2.pqr", mesh_density=mesh_value, mesh_generator="msms")
    protein2 = pbj.electrostatics.Solute("pqrs//sphere_point_r1q2_d3.pqr", mesh_density=mesh_value, mesh_generator="msms")
    simulation.add_solute(protein)
    simulation.add_solute(protein2)
    simulation.calculate_solvation_energy()
    solv_energy_complex = protein.results['solvation_energy'] + protein2.results['solvation_energy']
    solv_energy_binding = solv_energy_complex - 2*solv_energy_alone

    #Forces calculation   
    print('formulacion con la suma de terminos dielectric app')
    simulation.calculate_solvation_forces(formulation='full',dielectric_term='approx')
    f_solv_full_app = protein2.results['f_solv']
    fdb_app = protein2.results['f_db']
    print(protein.results['f_solv'])
    print(protein2.results['f_solv'])

    print('formulacion con la suma de terminos dielectric exact')
    simulation.calculate_solvation_forces(formulation='full',dielectric_term='exact')
    f_solv_full_ex = protein2.results['f_solv']
    print(protein.results['f_solv'])
    print(protein2.results['f_solv'])

    print('formulacion nueva')
    simulation.calculate_solvation_forces(formulation='fast')
    f_solv_fast = protein2.results['f_solv']
    print(protein.results['f_solv'])
    print(protein2.results['f_solv'])
    f.write('%d & %.4f & %.4f & %.4f & %.4f  \\\ \n'%(mesh_value,\
                                               f_solv_full_app[0], \
                                                f_solv_full_ex[0], \
                                               f_solv_fast[0],\
                                               solv_energy_binding))
    
    f_terms.write('%d & %.4f & %.4f & %.4f & %.4f & %.2f  \\\ \n'%(mesh_value,\
                                                     mag(protein.results["f_qf"]),\
                                                     mag(protein.results['f_db']),\
                                                     mag(fdb_app),\
                                                     mag(protein.results['f_ib']),\
                                                     protein.results['solvation_energy']))

    f.close()
    f_terms.close()

-----------------------------------
mesh value:  2
C:\Users\ianad\Desktop\paper_PBforces\pbj\mesh\ExternalSoftware\MSMS\msms.exe -if c:\Users\ianad\Desktop\paper_PBforces\mesh_temp\sphere_point_r1q2.xyzr -of c:\Users\ianad\Desktop\paper_PBforces\mesh_temp\sphere_point_r1q2 -p 1.4 -d 2 -no_header
C:\Users\ianad\Desktop\paper_PBforces\pbj\mesh\ExternalSoftware\MSMS\msms.exe -if c:\Users\ianad\Desktop\paper_PBforces\mesh_temp\sphere_point_r1q2.xyzr -of c:\Users\ianad\Desktop\paper_PBforces\mesh_temp\sphere_point_r1q2 -p 1.4 -d 2 -no_header
C:\Users\ianad\Desktop\paper_PBforces\pbj\mesh\ExternalSoftware\MSMS\msms.exe -if c:\Users\ianad\Desktop\paper_PBforces\mesh_temp\sphere_point_r1q2_d3.xyzr -of c:\Users\ianad\Desktop\paper_PBforces\mesh_temp\sphere_point_r1q2_d3 -p 1.4 -d 2 -no_header
formulacion con la suma de terminos dielectric app
[-1.89360621e+00  1.35473217e-02 -8.10361896e-07]
[ 1.89358004e+00  1.35489015e-02 -9.06926162e-07]
formulacion con la suma de terminos dielectric exact
[

### Virtual Work

In [41]:
# Trabajo virtual

mesh_vertA2_sim = [2,4,8,16]

for mesh_value in mesh_vertA2_sim:
    print('-----------------------------------')
    print('mesh value: ', mesh_value)

    simulation = pbj.electrostatics.Simulation()
    protein = pbj.electrostatics.Solute("notebooks\\tutorials\\pqrs\\sphere_point_r1q2.pqr", mesh_density=mesh_value, mesh_generator="msms")
    protein2 = pbj.electrostatics.Solute("notebooks\\tutorials\\pqrs\\sphere_point_r1q2_d3+h0.001.pqr", mesh_density=mesh_value, mesh_generator="msms")
    simulation.add_solute(protein)
    simulation.add_solute(protein2)
    simulation.calculate_solvation_energy()
    solv_energyh_adelante = protein2.results['solvation_energy']

    simulation = pbj.electrostatics.Simulation()
    protein = pbj.electrostatics.Solute("notebooks\\tutorials\\pqrs\\sphere_point_r1q2.pqr", mesh_density=mesh_value, mesh_generator="msms")
    protein2 = pbj.electrostatics.Solute("notebooks\\tutorials\\pqrs\\sphere_point_r1q2_d3-h0.001.pqr", mesh_density=mesh_value, mesh_generator="msms")
    simulation.add_solute(protein)
    simulation.add_solute(protein2)
    simulation.calculate_solvation_energy()
    solv_energyh_atras = protein2.results['solvation_energy']

    print('La fuerza en direccion x: %f kcal/molA usando desplazamiento virtuales y h=0.001' %float(-(solv_energyh_adelante - solv_energyh_atras) / 0.002))

-----------------------------------
mesh value:  2
C:\Users\ianad\Desktop\pbj\pbj\pbj\mesh\ExternalSoftware\MSMS\msms.exe -if c:\Users\ianad\Desktop\pbj\pbj\mesh_temp\sphere_point_r1q1.xyzr -of c:\Users\ianad\Desktop\pbj\pbj\mesh_temp\sphere_point_r1q1 -p 1.4 -d 2 -no_header
C:\Users\ianad\Desktop\pbj\pbj\pbj\mesh\ExternalSoftware\MSMS\msms.exe -if c:\Users\ianad\Desktop\pbj\pbj\mesh_temp\001.xyzr -of c:\Users\ianad\Desktop\pbj\pbj\mesh_temp\001 -p 1.4 -d 2 -no_header
C:\Users\ianad\Desktop\pbj\pbj\pbj\mesh\ExternalSoftware\MSMS\msms.exe -if c:\Users\ianad\Desktop\pbj\pbj\mesh_temp\sphere_point_r1q1.xyzr -of c:\Users\ianad\Desktop\pbj\pbj\mesh_temp\sphere_point_r1q1 -p 1.4 -d 2 -no_header
C:\Users\ianad\Desktop\pbj\pbj\pbj\mesh\ExternalSoftware\MSMS\msms.exe -if c:\Users\ianad\Desktop\pbj\pbj\mesh_temp\001.xyzr -of c:\Users\ianad\Desktop\pbj\pbj\mesh_temp\001 -p 1.4 -d 2 -no_header
La fuerza en direccion x: 0.234901 kcal/molA usando desplazamiento virtuales y h=0.001
------------------

### Simulation at several distances between centers 

In [5]:
dist_sim = [3,4,5,6,7,8,9,10,12,14,16,18,20]

for dist in dist_sim:
    
    # open a file to write the results
    f = open("results_pbj//sphere_r1q2_forces_to_latex_dist.txt", "a")
    f_terms = open("results_pbj//sphere_r1q2_forces_terms_to_latex_dist.txt", "a")
    print('-----------------------------------')
    print('Distance: %d A'%(dist))

    #Solvation energy alone
    simulation = pbj.electrostatics.Simulation()
    protein = pbj.electrostatics.Solute("pqrs//sphere_point_r1q2.pqr", mesh_density=8, mesh_generator="msms")
    simulation.add_solute(protein)
    simulation.calculate_solvation_energy()
    solv_energy_alone = protein.results['solvation_energy']

    #Solvation energy complex
    simulation = pbj.electrostatics.Simulation()
    protein = pbj.electrostatics.Solute("pqrs//sphere_point_r1q2.pqr", mesh_density=8, mesh_generator="msms")
    protein2 = pbj.electrostatics.Solute("pqrs//sphere_point_r1q2_d%d.pqr"%(dist), mesh_density=8, mesh_generator="msms")
    simulation.add_solute(protein)
    simulation.add_solute(protein2)
    simulation.calculate_solvation_energy()
    solv_energy_complex = protein.results['solvation_energy'] + protein2.results['solvation_energy']
    solv_energy_binding = solv_energy_complex - 2*solv_energy_alone

    #Forces calculation   
    print('formulacion con la suma de terminos')
    simulation.calculate_solvation_forces(formulation='full')
    f_solv_full = protein2.results['f_solv']
    print(protein.results['f_solv'])
    print(protein2.results['f_solv'])

    #Forces calculation   
    print('formulacion con la suma de terminos dielectric app')
    simulation.calculate_solvation_forces(formulation='full',dielectric_term='approx')
    f_solv_full_app = protein2.results['f_solv']
    fdb_app = protein2.results['f_db']
    print(protein.results['f_solv'])
    print(protein2.results['f_solv'])

    print('formulacion con la suma de terminos dielectric exact')
    simulation.calculate_solvation_forces(formulation='full',dielectric_term='exact')
    f_solv_full_ex = protein2.results['f_solv']
    print(protein.results['f_solv'])
    print(protein2.results['f_solv'])

    print('formulacion nueva')
    simulation.calculate_solvation_forces(formulation='fast')
    f_solv_fast = protein2.results['f_solv']
    print(protein.results['f_solv'])
    print(protein2.results['f_solv'])

    f.write('%d & %.4f & %.4f & %.4f & %.4f  \\\ \n'%(dist,\
                                               f_solv_full_app[0], \
                                                f_solv_full_ex[0], \
                                               f_solv_fast[0],\
                                               solv_energy_binding))
    
    f_terms.write('%d & %.4f & %.4f & %.4f & %.4f & %.2f  \\\ \n'%(dist,\
                                                     mag(protein.results["f_qf"]),\
                                                     mag(protein.results['f_db']),\
                                                     mag(fdb_app),\
                                                     mag(protein.results['f_ib']),\
                                                     protein.results['solvation_energy']))

    f.close()
    f_terms.close()

-----------------------------------
Distance: 3 A
C:\Users\ianad\Desktop\paper_PBforces\pbj\mesh\ExternalSoftware\MSMS\msms.exe -if c:\Users\ianad\Desktop\paper_PBforces\mesh_temp\sphere_point_r1q2.xyzr -of c:\Users\ianad\Desktop\paper_PBforces\mesh_temp\sphere_point_r1q2 -p 1.4 -d 8 -no_header
C:\Users\ianad\Desktop\paper_PBforces\pbj\mesh\ExternalSoftware\MSMS\msms.exe -if c:\Users\ianad\Desktop\paper_PBforces\mesh_temp\sphere_point_r1q2.xyzr -of c:\Users\ianad\Desktop\paper_PBforces\mesh_temp\sphere_point_r1q2 -p 1.4 -d 8 -no_header
C:\Users\ianad\Desktop\paper_PBforces\pbj\mesh\ExternalSoftware\MSMS\msms.exe -if c:\Users\ianad\Desktop\paper_PBforces\mesh_temp\sphere_point_r1q2_d3.xyzr -of c:\Users\ianad\Desktop\paper_PBforces\mesh_temp\sphere_point_r1q2_d3 -p 1.4 -d 8 -no_header
formulacion con la suma de terminos
[-1.94340595e+00 -5.07353802e-03  6.32840314e-05]
[ 1.94339841e+00 -5.07342431e-03 -6.37213383e-05]
formulacion con la suma de terminos dielectric app
[-1.86688985e+00 -4

## Barnase-Barstar complex

### Simulacion barnase alone

In [12]:
mesh_vertA2_sim = [2,4,8,16]

for mesh_value in mesh_vertA2_sim:
    f = open("notebooks//tutorials//barnase_forces_to_latex.txt", "a")
    print('-----------------------------------')
    print('mesh value: ', mesh_value)
    simulation = pbj.electrostatics.Simulation()
    protein = pbj.electrostatics.Solute("notebooks//tutorials//pqrs//1brs_BE_barnase.pqr", mesh_density=mesh_value)
    simulation.operator_assembler = 'fmm'
    protein.operator_assembler = "fmm"
    protein.rhs_constructor = "fmm"
    simulation.add_solute(protein)
    simulation.calculate_solvation_energy()

    print('formulacion con la suma de terminos')
    simulation.calculate_solvation_forces(formulation='full')
    f_solv_full = protein.results['f_solv']
    print(protein.results['f_solv'])

    print('formulacion nueva')
    simulation.calculate_solvation_forces(formulation='fast')
    f_solv_fast = protein.results['f_solv']
    print(protein.results['f_solv'])
    f.write('%d & %.4f & %.4f & %.6f  \\\ \n'%(mesh_value,mag(f_solv_full), mag(f_solv_fast), protein.results['solvation_energy']))
    f.close()

-----------------------------------
mesh value:  2


 <<INFO>> Starting NanoShaper 0.7.8
 <<INFO>> Loading atoms....
 <<INFO>> Read 1727 atoms
 <<INFO>> Geometric baricenter ->  -4.2595 23.3285 12.6551
 <<INFO>> Grid is 101
 <<INFO>> MAX 41.195 68.783 58.1096
 <<INFO>> MIN -49.714 -22.126 -32.7994
 <<INFO>> Perfil 50 %
 <<INFO>> Rmaxdim 46.327
 <<INFO>> Allocating memory...ok!
 <<INFO>> Initialization completed
 <<INFO>> Adjusting self intersection grid 
 <<INFO>> Self intersection grid is (before) 33
 <<INFO>> Self intersection grid is 32
 <<INFO>> Allocating self intersection grid....ok!
 <<INFO>> Computing alpha shape complex....ok!
 <<INFO>> Checking 236 probes for self intersections...ok!
 <<INFO>> Surface build-up time.. 0 [s]
 <<INFO>> Probe Radius value 1.4
 <<INFO>> Number of ses cells -> 4484
 <<INFO>> Number of del_point cells -> 702
 <<INFO>> Number of regular del_edge cells -> 2203
 <<INFO>> Number of singular del_edge cells -> 1
 <<INFO>> Number of regular del_facet cells

### Simulation barstar alone

In [13]:
mesh_vertA2_sim = [2,4,8,16]

for mesh_value in mesh_vertA2_sim:
    f = open("notebooks//tutorials//barstar_forces_to_latex.txt", "a")
    print('-----------------------------------')
    print('mesh value: ', mesh_value)
    simulation = pbj.electrostatics.Simulation()
    protein = pbj.electrostatics.Solute("notebooks//tutorials//pqrs//1brs_BE_barstar.pqr", mesh_density=mesh_value)
    simulation.operator_assembler = 'fmm'
    protein.operator_assembler = "fmm"
    protein.rhs_constructor = "fmm"
    simulation.add_solute(protein)
    simulation.calculate_solvation_energy()

    print('formulacion con la suma de terminos')
    simulation.calculate_solvation_forces(formulation='full')
    f_solv_full = protein.results['f_solv']
    print(protein.results['f_solv'])

    print('formulacion nueva')
    simulation.calculate_solvation_forces(formulation='fast')
    f_solv_fast = protein.results['f_solv']
    print(protein.results['f_solv'])
    f.write('%d & %.4f & %.4f & %.6f  \\\ \n'%(mesh_value,mag(f_solv_full), mag(f_solv_fast), protein.results['solvation_energy']))
    f.close()

-----------------------------------
mesh value:  2


 <<INFO>> Starting NanoShaper 0.7.8
 <<INFO>> Loading atoms....
 <<INFO>> Read 1381 atoms
 <<INFO>> Geometric baricenter ->  -2.1761 13.3966 34.994
 <<INFO>> Grid is 85
 <<INFO>> MAX 36.0057 51.5784 73.1758
 <<INFO>> MIN -40.3579 -24.7852 -3.18782
 <<INFO>> Perfil 50 %
 <<INFO>> Rmaxdim 38.248
 <<INFO>> Allocating memory...ok!
 <<INFO>> Initialization completed
 <<INFO>> Adjusting self intersection grid 
 <<INFO>> Self intersection grid is (before) 27
 <<INFO>> Self intersection grid is 16
 <<INFO>> Allocating self intersection grid....ok!
 <<INFO>> Computing alpha shape complex....ok!
 <<INFO>> Checking 184 probes for self intersections...ok!
 <<INFO>> Surface build-up time.. 0 [s]
 <<INFO>> Probe Radius value 1.4
 <<INFO>> Number of ses cells -> 3360
 <<INFO>> Number of del_point cells -> 536
 <<INFO>> Number of regular del_edge cells -> 1658
 <<INFO>> Number of singular del_edge cells -> 0
 <<INFO>> Number of regular del_facet cel

### Simulacion barstar-barnase complex with 4 vert/$\AA ^2$ at several distances

In [14]:
# Metodos Bem

distances = [9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,100]

for dist in distances:
    # open a file to write the results
    f = open("notebooks//tutorials//barnase-barstar_forces_to_latex_mesh4.txt", "a")
    print('-----------------------------------')
    print('Distance: ', dist)

    simulation = pbj.electrostatics.Simulation()
    protein = pbj.electrostatics.Solute("notebooks//tutorials//pqrs//1brs_BE_barnase.pqr", mesh_density=4)
    protein2 = pbj.electrostatics.Solute("notebooks//tutorials//pqrs//1brs_BE_barstar_d%d.pqr"%(dist), mesh_density=4)
    simulation.add_solute(protein)
    simulation.add_solute(protein2)
    simulation.operator_assembler = 'fmm'
    protein.operator_assembler = "fmm"
    protein.rhs_constructor = "fmm"
    protein2.operator_assembler = "fmm"
    protein2.rhs_constructor = "fmm"

    print('formulacion con la suma de terminos')
    simulation.calculate_solvation_energy()
    binding_energy = (protein.results['solvation_energy'] + protein2.results['solvation_energy'])-(-318.51+-401.97)
    simulation.calculate_solvation_forces(formulation='full')
    f_solv_full1 = protein.results['f_solv']
    f_solv_full2 = protein2.results['f_solv']
    print(protein.results['f_solv'])
    print(protein2.results['f_solv'])

    print('formulacion nueva')
    simulation.calculate_solvation_forces(formulation='fast')
    f_solv_fast1 = protein.results['f_solv']
    f_solv_fast2 = protein2.results['f_solv']
    print(protein.results['f_solv'])
    print(protein2.results['f_solv'])
    f.write('%d & %.4f & %.4f & %.4f & %.4f & %.6f & %.6f & %.6f  \\\ \n'%(dist,f_solv_full1[2], f_solv_fast1[2],\
                                                        f_solv_full2[2], f_solv_fast2[2],binding_energy,\
                                                        protein.results['solvation_energy'], protein2.results['solvation_energy'] ))

    f.close()

-----------------------------------
Distance:  10


 <<INFO>> Starting NanoShaper 0.7.8
 <<INFO>> Loading atoms....
 <<INFO>> Read 1727 atoms
 <<INFO>> Geometric baricenter ->  -4.2595 23.3285 12.6551
 <<INFO>> Grid is 149
 <<INFO>> MAX 41.9905 69.5785 58.9051
 <<INFO>> MIN -50.5095 -22.9215 -33.5949
 <<INFO>> Perfil 50 %
 <<INFO>> Rmaxdim 46.327
 <<INFO>> Allocating memory...ok!
 <<INFO>> Initialization completed
 <<INFO>> Adjusting self intersection grid 
 <<INFO>> Self intersection grid is (before) 33
 <<INFO>> Self intersection grid is 32
 <<INFO>> Allocating self intersection grid....ok!
 <<INFO>> Computing alpha shape complex....ok!
 <<INFO>> Checking 236 probes for self intersections...ok!
 <<INFO>> Surface build-up time.. 0 [s]
 <<INFO>> Probe Radius value 1.4
 <<INFO>> Number of ses cells -> 4484
 <<INFO>> Number of del_point cells -> 702
 <<INFO>> Number of regular del_edge cells -> 2203
 <<INFO>> Number of singular del_edge cells -> 1
 <<INFO>> Number of regular del_facet ce

### Simulacion barstar-barnase complex with 8 vert/$\AA ^2$ at several distances

In [8]:
# Metodos Bem

distances = [9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,100]

for dist in distances:
    # open a file to write the results
    f = open("notebooks//tutorials//barnase-barstar_forces_to_latex_mesh8.txt", "a")
    print('-----------------------------------')
    print('Distance: ', dist)

    simulation = pbj.electrostatics.Simulation()
    protein = pbj.electrostatics.Solute("notebooks//tutorials//pqrs//1brs_BE_barnase.pqr", mesh_density=8)
    protein2 = pbj.electrostatics.Solute("notebooks//tutorials//pqrs//1brs_BE_barstar_d%d.pqr"%(dist), mesh_density=8)
    simulation.add_solute(protein)
    simulation.add_solute(protein2)
    simulation.operator_assembler = 'fmm'
    protein.operator_assembler = "fmm"
    protein.rhs_constructor = "fmm"
    protein2.operator_assembler = "fmm"
    protein2.rhs_constructor = "fmm"

    print('formulacion con la suma de terminos')
    simulation.calculate_solvation_energy()
    simulation.calculate_solvation_forces(formulation='full')
    binding_energy = (protein.results['solvation_energy'] + protein2.results['solvation_energy'])-(-312.703404+-395.316315)
    f_solv_full1 = protein.results['f_solv']
    f_solv_full2 = protein2.results['f_solv']
    print(protein.results['f_solv'])
    print(protein2.results['f_solv'])

    print('formulacion nueva')
    simulation.calculate_solvation_forces(formulation='fast')
    f_solv_fast1 = protein.results['f_solv']
    f_solv_fast2 = protein2.results['f_solv']
    print(protein.results['f_solv'])
    print(protein2.results['f_solv'])
    f.write('%d & %.4f & %.4f & %.4f & %.4f & %.6f & %.6f & %.6f  \\\ \n'%(dist,f_solv_full1[2], f_solv_fast1[2],\
                                                        f_solv_full2[2], f_solv_fast2[2],binding_energy,\
                                                        protein.results['solvation_energy'],protein2.results['solvation_energy']))

    f.close()

-----------------------------------
Distance:  20


 <<INFO>> Starting NanoShaper 0.7.8
 <<INFO>> Loading atoms....
 <<INFO>> Read 1727 atoms
 <<INFO>> Geometric baricenter ->  -4.2595 23.3285 12.6551
 <<INFO>> Grid is 213
 <<INFO>> MAX 41.8275 69.4155 58.7421
 <<INFO>> MIN -50.3465 -22.7585 -33.4319
 <<INFO>> Perfil 50 %
 <<INFO>> Rmaxdim 46.327
 <<INFO>> Allocating memory...ok!
 <<INFO>> Initialization completed
 <<INFO>> Adjusting self intersection grid 
 <<INFO>> Self intersection grid is (before) 33
 <<INFO>> Self intersection grid is 32
 <<INFO>> Allocating self intersection grid....ok!
 <<INFO>> Computing alpha shape complex....ok!
 <<INFO>> Checking 236 probes for self intersections...ok!
 <<INFO>> Surface build-up time.. 0 [s]
 <<INFO>> Probe Radius value 1.4
 <<INFO>> Number of ses cells -> 4484
 <<INFO>> Number of del_point cells -> 702
 <<INFO>> Number of regular del_edge cells -> 2203
 <<INFO>> Number of singular del_edge cells -> 1
 <<INFO>> Number of regular del_facet ce

/home/ianaddisonsmith/miniconda3/envs/pbj_dev/lib/python3.9/site-packages/pyopencl/__init__.py:274: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  warn("Non-empty compiler output encountered. Set the "
/home/ianaddisonsmith/miniconda3/envs/pbj_dev/lib/python3.9/site-packages/pyopencl/__init__.py:274: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  warn("Non-empty compiler output encountered. Set the "
/home/ianaddisonsmith/miniconda3/envs/pbj_dev/lib/python3.9/site-packages/pyopencl/__init__.py:274: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  warn("Non-empty compiler output encountered. Set the "
/home/ianaddisonsmith/miniconda3/envs/pbj_dev/lib/python3.9/site-packages/pyopencl/__init__.py:274: CompilerWarning: Non-empty compiler output encountered

[ 0.17116385 -0.21016746  0.15257971]
[-0.0055383  -0.22701884 -0.03349448]
formulacion nueva
[0.005641   0.03115268 0.01076407]
[-0.01153863  0.01164596 -0.01454281]
-----------------------------------
Distance:  100


 <<INFO>> Starting NanoShaper 0.7.8
 <<INFO>> Loading atoms....
 <<INFO>> Read 1727 atoms
 <<INFO>> Geometric baricenter ->  -4.2595 23.3285 12.6551
 <<INFO>> Grid is 213
 <<INFO>> MAX 41.8275 69.4155 58.7421
 <<INFO>> MIN -50.3465 -22.7585 -33.4319
 <<INFO>> Perfil 50 %
 <<INFO>> Rmaxdim 46.327
 <<INFO>> Allocating memory...ok!
 <<INFO>> Initialization completed
 <<INFO>> Adjusting self intersection grid 
 <<INFO>> Self intersection grid is (before) 33
 <<INFO>> Self intersection grid is 32
 <<INFO>> Allocating self intersection grid....ok!
 <<INFO>> Computing alpha shape complex....ok!
 <<INFO>> Checking 236 probes for self intersections...ok!
 <<INFO>> Surface build-up time.. 0 [s]
 <<INFO>> Probe Radius value 1.4
 <<INFO>> Number of ses cells -> 4484
 <<INFO>> Numbe